spring:
  datasource:
    #url: jdbc:h2:tcp://localhost:9092/C:/opt/fedex/sabre/h2db/moviesdb
    #url: jdbc:h2:/C:/opt/fedex/sabre/h2db/moviesdb
    url: jdbc:h2:mem:moviesdb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create 
server:
  port: ${PORT:6001}
moviesapi:
  roles:
  - name: DIRECTOR
  - name: SCREENWRITER
  - name: PRODUCER
  - name: COMMON PEOPLE  
  persons:
  - id: Chiranjeevi
    name: Chiranjeevi
  - id: Nagarjuna
    name: Nagarjuna
  - id: Charan
    name: Charan
  - id: User 1
    name: User 1
  - id: User 2
    name: User 2
  - id: User 3
    name: User 3
  movies:
  - movieId:  
    title: Geetha Govindham
    imageUrl: /gallery/xyz.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: '@Narthanasala'
    imageUrl: /gallery/n.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: Neevevaro
    imageUrl: /gallery/neevevaro.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: Bharat Ane Nenu
    imageUrl: /gallery/bharatanenenu.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: Goodachari
    imageUrl: /gallery/goodachari.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: Srinivasa Kalyanam
    imageUrl: /gallery/srinivasakalyanam.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0  
  - movieId:  
    title: Viswaroopam
    imageUrl: /gallery/viswaroopam.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0 
  - movieId:  
    title: Saakshyam
    imageUrl: /gallery/saakshyam.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: Hello Guru Prema Kosame
    imageUrl: /gallery/hello-guru-prema-kosame.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: Pandemkodi 2
    imageUrl: /gallery/pandemkodi-2.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0  
  - movieId:  
    title: Aravindha Sametha
    imageUrl: /gallery/aravinda-sametha.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0 
  - movieId:  
    title: NOTA
    imageUrl: /gallery/nota.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: Bale Manchi Chowka Beram
    imageUrl: /gallery/bale-manchi-chowka-beram.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: DesamLo Dongalu Paddaru
    imageUrl: /gallery/desamlo-dongalu-paddaru.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0  
  - movieId:  
    title: Natakam
    imageUrl: /gallery/natakam.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0  
  - movieId:  
    title: Nawab
    imageUrl: /gallery/nawab.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0
  - movieId:  
    title: Devadas
    imageUrl: /gallery/devadas.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0  
  - movieId:  
    title: Ee Maya Peremito
    imageUrl: /gallery/ee-maya-peremito.jpg
    tagline: family movie
    hitRate: 0
    flopRate: 0                    
movieRatings: 
- movieTitle: A
  userName: Chiranjeevi
  rating: HIT
- movieTitle: B
  userName: Chiranjeevi
  rating: FLOP 
- movieTitle: A
  userName: Nagarjuna
  rating: HIT 
- movieTitle: B
  userName: Nagarjuna
  rating: HIT
- movieTitle: A
  userName: Charan
  rating: FLOP 
- movieTitle: B
  userName: Charan
  rating: FLOP                           